package pojo;

// default package
// Generated Aug 2, 2020 8:53:50 PM by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Docgia generated by hbm2java
 */
public class Docgia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String madocgia;
	private String hoten;
	private String loaidocgia;
	private Date ngaysinh;
	private String Diachi;
	private String email;
	private Date ngaylapthe;
	private Set<Phieumuonsach> phieumuonsaches = new HashSet<Phieumuonsach>(0);

	public Docgia() {
	}

	public Docgia(String madocgia) {
		this.madocgia = madocgia;
	}

	public Docgia(String madocgia, String hoten, String loaidocgia, Date ngaysinh, String Diachi, String email, Date ngaylapthe, Set<Phieumuonsach> phieumuonsaches) {
       this.madocgia = madocgia;
       this.hoten = hoten;
       this.loaidocgia = loaidocgia;
       this.ngaysinh = ngaysinh;
       this.Diachi = Diachi;
       this.email = email;
       this.ngaylapthe = ngaylapthe;
       this.phieumuonsaches = phieumuonsaches;
    }

	public String getMadocgia() {
		return this.madocgia;
	}

	public void setMadocgia(String madocgia) {
		this.madocgia = madocgia;
	}

	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	public String getLoaidocgia() {
		return this.loaidocgia;
	}

	public void setLoaidocgia(String loaidocgia) {
		this.loaidocgia = loaidocgia;
	}

	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	public String getDiachi() {
        return this.Diachi;
    }

	public void setDiachi(String Diachi) {
        this.Diachi = Diachi;
    }

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getNgaylapthe() {
		return this.ngaylapthe;
	}

	public void setNgaylapthe(Date ngaylapthe) {
		this.ngaylapthe = ngaylapthe;
	}

	public Set<Phieumuonsach> getPhieumuonsaches() {
		return this.phieumuonsaches;
	}

	public void setPhieumuonsaches(Set<Phieumuonsach> phieumuonsaches) {
		this.phieumuonsaches = phieumuonsaches;
	}

}
