package pojo;

// default package
// Generated Aug 2, 2020 8:53:50 PM by Hibernate Tools 5.4.14.Final

/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String username;
	private String password;
	private String hoten;
	private Integer loainguoidung;
	private String email;

	public Nguoidung() {
	}

	public Nguoidung(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Nguoidung(String username, String password, String hoten, Integer loainguoidung, String email) {
		this.username = username;
		this.password = password;
		this.hoten = hoten;
		this.loainguoidung = loainguoidung;
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	public Integer getLoainguoidung() {
		return this.loainguoidung;
	}

	public void setLoainguoidung(Integer loainguoidung) {
		this.loainguoidung = loainguoidung;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
