package pojo;// default package
// Generated Aug 2, 2020 8:53:50 PM by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieumuonsach generated by hbm2java
 */
public class Phieumuonsach implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maphieu;
	private Docgia docgia;
	private Date ngaymuon;
	private Set<Sach> sachmuons = new HashSet<Sach>(0);

	public Phieumuonsach() {
	}

	public Phieumuonsach(String maphieu) {
		this.maphieu = maphieu;
	}

	public Phieumuonsach(String maphieu, Docgia docgia, Date ngaymuon, Set<Sach> sachmuons) {
		this.maphieu = maphieu;
		this.docgia = docgia;
		this.ngaymuon = ngaymuon;
		this.sachmuons = sachmuons;
	}

	public String getMaphieu() {
		return this.maphieu;
	}

	public void setMaphieu(String maphieu) {
		this.maphieu = maphieu;
	}

	public Docgia getDocgia() {
		return this.docgia;
	}

	public void setDocgia(Docgia docgia) {
		this.docgia = docgia;
	}

	public Date getNgaymuon() {
		return this.ngaymuon;
	}

	public void setNgaymuon(Date ngaymuon) {
		this.ngaymuon = ngaymuon;
	}

	public Set<Sach> getSachmuons() {
		return this.sachmuons;
	}

	public void setSachmuons(Set<Sach> sachmuons) {
		this.sachmuons = sachmuons;
	}

}
