package pojo;// default package
// Generated Aug 2, 2020 8:53:50 PM by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sach generated by hbm2java
 */
public class Sach implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String masach;
	private Theloai theloai;
	private String tensach;
	private String tacgia;
	private Date namxuatban;
	private String nhaxuatban;
	private Date ngaynhap;
	private Set<Sachmuon> sachmuons = new HashSet<Sachmuon>(0);

	public Sach() {
	}

	public Sach(String masach) {
		this.masach = masach;
	}

	public Sach(String masach, Theloai theloai, String tensach, String tacgia, Date namxuatban, String nhaxuatban,
			Date ngaynhap, Set<Sachmuon> sachmuons) {
		this.masach = masach;
		this.theloai = theloai;
		this.tensach = tensach;
		this.tacgia = tacgia;
		this.namxuatban = namxuatban;
		this.nhaxuatban = nhaxuatban;
		this.ngaynhap = ngaynhap;
		this.sachmuons = sachmuons;
	}

	public String getMasach() {
		return this.masach;
	}

	public void setMasach(String masach) {
		this.masach = masach;
	}

	public Theloai getTheloai() {
		return this.theloai;
	}

	public void setTheloai(Theloai theloai) {
		this.theloai = theloai;
	}

	public String getTensach() {
		return this.tensach;
	}

	public void setTensach(String tensach) {
		this.tensach = tensach;
	}

	public String getTacgia() {
		return this.tacgia;
	}

	public void setTacgia(String tacgia) {
		this.tacgia = tacgia;
	}

	public Date getNamxuatban() {
		return this.namxuatban;
	}

	public void setNamxuatban(Date namxuatban) {
		this.namxuatban = namxuatban;
	}

	public String getNhaxuatban() {
		return this.nhaxuatban;
	}

	public void setNhaxuatban(String nhaxuatban) {
		this.nhaxuatban = nhaxuatban;
	}

	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	public Set<Sachmuon> getSachmuons() {
		return this.sachmuons;
	}

	public void setSachmuons(Set<Sachmuon> sachmuons) {
		this.sachmuons = sachmuons;
	}

}
