package pojo;// default package
// Generated Aug 2, 2020 8:53:50 PM by Hibernate Tools 5.4.14.Final

/**
 * SachmuonId generated by hbm2java
 */
public class SachmuonId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maphieu;
	private String masach;

	public SachmuonId() {
	}

	public SachmuonId(String maphieu) {
		this.maphieu = maphieu;
	}

	public SachmuonId(String maphieu, String masach) {
		this.maphieu = maphieu;
		this.masach = masach;
	}

	public String getMaphieu() {
		return this.maphieu;
	}

	public void setMaphieu(String maphieu) {
		this.maphieu = maphieu;
	}

	public String getMasach() {
		return this.masach;
	}

	public void setMasach(String masach) {
		this.masach = masach;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SachmuonId))
			return false;
		SachmuonId castOther = (SachmuonId) other;

		return ((this.getMaphieu() == castOther.getMaphieu()) || (this.getMaphieu() != null
				&& castOther.getMaphieu() != null && this.getMaphieu().equals(castOther.getMaphieu())))
				&& ((this.getMasach() == castOther.getMasach()) || (this.getMasach() != null
						&& castOther.getMasach() != null && this.getMasach().equals(castOther.getMasach())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaphieu() == null ? 0 : this.getMaphieu().hashCode());
		result = 37 * result + (getMasach() == null ? 0 : this.getMasach().hashCode());
		return result;
	}

}
