package pojo;// default package
// Generated Aug 2, 2020 8:53:50 PM by Hibernate Tools 5.4.14.Final

/**
 * Thamso generated by hbm2java
 */
public class Thamso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String mathamso;
	private String tenthamso;
	private String kieu;
	private String giatri;
	private String tinhtrang;

	public Thamso() {
	}

	public Thamso(String mathamso) {
		this.mathamso = mathamso;
	}

	public Thamso(String mathamso, String tenthamso, String kieu, String giatri, String tinhtrang) {
		this.mathamso = mathamso;
		this.tenthamso = tenthamso;
		this.kieu = kieu;
		this.giatri = giatri;
		this.tinhtrang = tinhtrang;
	}

	public String getMathamso() {
		return this.mathamso;
	}

	public void setMathamso(String mathamso) {
		this.mathamso = mathamso;
	}

	public String getTenthamso() {
		return this.tenthamso;
	}

	public void setTenthamso(String tenthamso) {
		this.tenthamso = tenthamso;
	}

	public String getKieu() {
		return this.kieu;
	}

	public void setKieu(String kieu) {
		this.kieu = kieu;
	}

	public String getGiatri() {
		return this.giatri;
	}

	public void setGiatri(String giatri) {
		this.giatri = giatri;
	}

	public String getTinhtrang() {
		return this.tinhtrang;
	}

	public void setTinhtrang(String tinhtrang) {
		this.tinhtrang = tinhtrang;
	}

}
